services:
  backend:
    build: ./server
    image: my-diary-server-image
    container_name: my-diary-server-container
    ports:
      - "5656:5656"
    env_file:
      - ./server/.env
    networks:
      - diary-network
  frontend:
    build: ./client
    image: my-diary-client-image
    container_name: my-diary-client-container
    ports:
      - "5273:5273"
    depends_on:
      - backend
    env_file:
      - ./client/.env
    networks:
      - diary-network

networks:
  diary-network:
    driver: bridge